FROM registry.access.redhat.com/ubi8/openjdk-11-runtime:1.14

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

COPY --chown=185 target/*.jar /deployments/app.jar

EXPOSE 8080
USER 185
ENV JAVA_APP_JAR="/deployments/app.jar"
